//PRODUCTS
export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

//CUSTOMERS
export const CUSTOMERS_LIST_REQUEST = 'CUSTOMERS_LIST_REQUEST'
export const CUSTOMERS_LIST_SUCCESS = 'CUSTOMERS_LIST_SUCCESS'
export const CUSTOMERS_LIST_FAIL = 'CUSTOMERS_LIST_FAIL'

export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST'
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS'
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL'

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST'
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS'
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL'

//USERS
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

//STATES
export const STATES_LIST_REQUEST = 'STATES_LIST_REQUEST'
export const STATES_LIST_SUCCESS = 'STATES_LIST_SUCCESS'
export const STATES_LIST_FAIL = 'STATES_LIST_FAIL'

