export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER'
export const CUSTOMERS_ERROR = 'CUSTOMERS_ERROR'
export const CLEAR_CURRENT = 'CLEAR_CURRENT'
export const SET_LOADING = 'SET_LOADING'

export const CUSTOMERS_LIST_REQUEST = 'CUSTOMERS_LIST_REQUEST'
export const CUSTOMERS_LIST_SUCCESS = 'CUSTOMERS_LIST_SUCCESS'
export const CUSTOMERS_LIST_FAIL = 'CUSTOMERS_LIST_FAIL'

export const CUSTOMER_ADD_REQUEST = 'CUSTOMER_ADD_REQUEST'
export const CUSTOMER_ADD_SUCCESS = 'CUSTOMER_ADD_SUCCESS'
export const CUSTOMER_ADD_FAIL = 'CUSTOMER_ADD_FAIL'


